#56059 chore(huskry)

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -10,24 +10,24 @@ status=$?
 set -e
 
 if [ $status -ne 0 ]; then
-    echo ""
-    echo "❌ Invalid commit message format"
-    echo ""
-    echo "✅ Correct Format →  <task number> <type>(<scope>): <subject>"
-    echo ""
-    echo "📑 Examples:"
-    echo "    #3334 feat: add login functionality"
-    echo "    #03004 fix(ui): correct button alignment"
-    echo ""
-    echo echo "💢 Allowed types:🔸 feat → new feature"
-    echo "                      🔸 fix → bug fix"
-    echo "                      🔸 docs → documentation only changes"
-    echo "                      🔸 style → formatting, missing semi-colons, etc"
-    echo "                      🔸 refactor → code change that neither fixes a bug nor adds a feature"
-    echo "                      🔸 perf → a code change that improves performance"
-    echo "                      🔸 test → adding missing tests or correcting existing tests"
-    echo "                      🔸 chore → changes to the build process or auxiliary tools"
-    echo "                      🔸 ci → CI related changes"
-    echo ""
-    exit 1
+   echo ""
+   echo "❌ Invalid commit message format"
+   echo ""
+   echo "✅ Correct Format →  <task number> <type>(<scope>): <subject>"
+   echo ""
+   echo "📑 Examples:"
+   echo "    #3334 feat: add login functionality"
+   echo "    #03004 fix(ui): correct button alignment"
+   echo ""
+   echo echo "💢 Allowed types:🔸 feat → new feature"
+   echo "                      🔸 fix → bug fix"
+   echo "                      🔸 docs → documentation only changes"
+   echo "                      🔸 style → formatting, missing semi-colons, etc"
+   echo "                      🔸 refactor → code change that neither fixes a bug nor adds a feature"
+   echo "                      🔸 perf → a code change that improves performance"
+   echo "                      🔸 test → adding missing tests or correcting existing tests"
+   echo "                      🔸 chore → changes to the build process or auxiliary tools"
+   echo "                      🔸 ci → CI related changes"
+   echo ""
+   exit 1
 fi
